config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    member do
      put 'like', to: "posts#like_or_dislike"
      put 'dislike', to: "posts#like_or_dislike"
    end

    resources :comments do
      member do
        put 'like', to: "comments#like_or_dislike"
        put 'dislike', to: "comments#like_or_dislike"
      end
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  has_rich_text :content

  belongs_to :user
  belongs_to :post, counter_cache: true
end

app/models/post.rb
class Post < ApplicationRecord
    has_rich_text :content

    belongs_to :user
    has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable, :trackable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, except: %i[show like_or_dislike]
    before_action :set_post, only: %i[create edit update destroy like_or_dislike ]
    before_action :set_comment, only: %i[edit update like_or_dislike destroy]
    # POST /posts or /posts.json
    def create
      @comment = @post.comments.new(comment_params)

      respond_to do |format|
        if @comment.save
          format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @comment.errors, status: :unprocessable_entity }
        end
      end
    end

    def edit
    end
    # PATCH/PUT /posts/1 or /posts/1.json
    def update
      respond_to do |format|
        if @comment.update(comment_params)
          format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @comment.errors, status: :unprocessable_entity }
        end
      end
    end

    def like_or_dislike
      if request.path.end_with?("dislike")
        @comment.dislike_count +=1
      else
        @comment.like_count +=1
      end

      respond_to do |format|
        if @comment.save
          format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @comment.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /posts/1 or /posts/1.json
    def destroy
      @comment.destroy!

      respond_to do |format|
        format.html { redirect_to @post, notice: "Post was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_post
        @post = Post.find(params[:post_id])
      end

      def set_comment
        @comment = @post.comments.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def comment_params
        params.require(:comment).permit(:content)
      end
  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show like_or_dislike]
  before_action :set_post, only: %i[ show edit update destroy like_or_dislike ]

  # GET /posts or /posts.json
  def index
    @posts_by_year = Post.limit(100).order(id: :desc).group_by { |post| post.created_at.year }
  end

  # GET /posts/1 or /posts/1.json
  def show
    @comments = @post.comments.order(id: :desc)
    @comment = @post.comments.new
  end

  # GET /posts/new
  def new
    @post = current_user.posts.new
  end

  # GET /posts/1/edit
  def edit
    authorize @post
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    authorize @post
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def like_or_dislike
    if request.path.end_with?("dislike")
      @post.dislike_count +=1
    else
      @post.like_count +=1
    end

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    authorize @post
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content, :is_published)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/comments/_form.html.erb
<%= form_with(model: [post, comment], scope: comment) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.rich_text_area :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/_index.html.erb
<div class="comments">
  <% comments.each do |comment| %>
    <p>
      <div><%= comment.content %> </div>
      <div>Likes: <%= comment.like_count %> | Dislikes: <%= comment.dislike_count %></div>
      <div>
        <%= button_to "Like", like_post_comment_path(post, comment), method: :put %> | <%= button_to "Dislike", dislike_post_comment_path(post, comment), method: :put %>
        <%= link_to "Edit", edit_post_comment_path(post, comment) %>
        <%= button_to "Delete", [post, comment], method: :delete %>
      </div>
    </p>
  <% end %>
</div>

app/views/comments/_new.html.erb
<h2>New comment</h2>

<%= render "comments/form", post: post, comment: comment%>

app/views/comments/edit.html.erb
<h1>Edit comment</h1>

<%= render "form", post: @post, comment: @comment%>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="w-full bg-white">
    <div class="px-[446px]">
      <%= render "shared/header" %>
      <% if notice.present? || alert.present? %>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<div class="w-[720px] mx-auto">
  <div class="mb-10">
    <div class="mb-5">
      <div class="font-medium text-lg text-gray-850">Deepak Kumar</div>
      <div class="font-light text-sm text-gray-850">@deepak</div>
    </div>

    <div class="font-light text-base text-gray-700 mb-5">
      Digital product designer living and working in Bengaluru who enjoys building things. Currently leading designs at Kaleyra. Also, Barback at a cafe under construction.
    </div>

    <div class="flex flex-row radius-2 justify-between bg-gray-50 p-4 font-light text-sm text-gray-850 drop-shadow-lg">
      <div class="">Now and then, I send bite-sized notes about this and that to your inbox.</div>
      <div class="underline"><%= link_to "Subscribe", "#" %></div>
    </div>
  </div>

  <div class="font-light text-base text-gray-700 mb-5">
    This website is my digital garden.
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.rich_text_area :content %>
  </div>

  <div>
    <%= form.label :is_published, style: "display: block" %>
    <%= form.check_box :is_published %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="p-8 bg-white rounded">
  <div class="text-center">
    <span class="text-3xl text-primary"><%= post.title %></span>
  </div>

  <div>
    <%= post.content %>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<div class="w-[720px] mx-auto flex border rounded items-center drop-shadow">
  <label for="posts-search">
    <%= image_tag "icons/Search.png", class: "w-6 h-6 ml-2" %>
  </label>
  <input id="posts-search" type="text" class="flex-1 px-2 py-2 rounded font-light text-base text-gray-500 border-none border-transparent focus:border-transparent focus:ring-0" style="background: transparent;" placeholder="Search posts ..." />
</div>

<div class="w-[720px] mx-auto">
  <div class="my-10">
      <% @posts_by_year.each do |year, posts| %>
          <div class="font-light text-2xl text-gray-700 mb-5">Year <%= year %></div>
          <% posts.each do |post| %>
            <div class="border-b py-2">
              <div class="flex font-light text-base text-gray-700 place-content-end"><%= post.created_at.to_fs(:stamp) %></div>
              <div class="font-light text-lg text-gray-850">
                <%= link_to post.title, post, class: "pointer" %>
              </div>
              <% if user_signed_in? %>
                <div class="font-light text-base text-gray-700 ">
                  <span><small><%= post.is_published ? "Published" : "Unpublished" %></small></span>
                </div>
              <% end %>
            </div>
          <% end %>
      <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<div class="container p-4 bg-opacity-50 bg-space">

  <div class="m-2">
    <div class="flex justify-between my-2">
      <%= render "shared/ui/link_button", text: "Back", url: posts_path %>
      <div class="flex gap-4 place-content-end">
        <% if policy(@post).edit? %>
          <%= render "shared/ui/link_button", text: "Edit", url: edit_post_path(@post) %>
        <% end %>
        <% if policy(@post).delete? %>
          <%= render "shared/ui/danger_button", text: "Delete", url: post_path(@post) %>
        <% end %>
      </div>
    </div>
    <%= render @post %>
  </div>

  <div class="p-2 m-2 bg-white">
    <div class="flex gap-4">
      <%= render "shared/ui/default_button", text: "Like", url: like_post_path(@post) %>
      <span class="self-end text-sm"><%= @post.like_count%></span>
      <%= render "shared/ui/default_button", text: "Dislike", url: dislike_post_path(@post) %>
      <span class="self-end text-sm"><%= @post.dislike_count%></span>
    </div>
  </div>
</div>

<%   policy(@comment).new? do %>
  <%= render "comments/new", post: @post, comment: @comment %>
<% end %>

<h2>Comments (<%= @post.comments_count %>)</h2>
<%= render "comments/index", post: @post, comments: @comments %>

app/views/shared/_header.html.erb
<header class="w-[720px] mx-auto my-10">
    <nav>
        <div class="flex flex-wrap justify-between">
            <div class="lhs">
                <%= link_to root_path, class: "text-gray-850 font-light pointer" do %>
                  <%= image_tag "icons/Logo.png", class: "w-4 h-6" %>
                <% end %>
            </div>
            <div class="rhs flex gap-8">
                <% if user_signed_in? %>
                    <%= link_to "New Post", new_post_path, class: "text-base-850 font-thin pointer" %>
                    <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete }, class: "text-base-850 font-thin pointer" %>
                <% else %>
                    <%= link_to "Posts", posts_path, class: "text-gray-850 font-thin pointer" %>
                    <%= link_to "About", "#", class: "text-gray-850 font-thin pointer" %>
                    <%= link_to "#", class: "text-gray-850 font-thin pointer" do %>
                      <%= image_tag "icons/Toggle.png", class: "w-6 h-6" %>
                    <% end %>
                <% end %>
            </div>
        </div>
    </nav>
</header>

app/views/shared/ui/_danger_button.html.erb
<%= button_to text, url, method: :delete, class: "rounded text-danger border border-danger p-2 min-w-20 text-center bg-white" %>

app/views/shared/ui/_default_button.html.erb
<%= button_to text, url, method: :put, class: "rounded text-primary border border-secondary p-2 min-w-20 text-center bg-white" %>

app/views/shared/ui/_link_button.html.erb
<%= link_to text, url, class: "text-primary rounded border border-secondary p-2 min-w-20 text-center bg-white" %>